# A representation of a parameter for a UML model
# Description:     
#   This acts as a parameter for a method
# Course:   CSCI 420 - Software Engineering
# Authors:  Adisa, Amy, Carli, David, Joan
# Date:     October 21 2020

##########################################################################
# Imports

from models.Variable import Variable

##########################################################################

class UMLParameter(Variable):

    def get_raw_data(self):
        """Returns a JSON convertible form of the data"""
        return { 
            "type" : self.type,
            "name" : self.name
        }
    
    @staticmethod
    def from_raw_data(data):
        """Constructs a UMLParameter object from a set of data

        Precondition:
        - The data should have been generated by a call to get_raw_data()
        """
        return UMLParameter(data["type"], data["name"])


##########################################################################
